### ISSUE TITLE
Examples: Color #1e1e1e isn't in the palette

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/next-type#8]
We might as well use colors that are in the palette in our own examples, such as in:
```scss
.component__text {
	@include nTypeTextSans(3);
	color: #1e1e1e;
}
```
